name: mapping_workshop
channels:
  - defaults
  - conda-forge/label/broken
  - conda-forge
dependencies:
  - certifi=2022.9.24
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.8.13
  - readline=8.2
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - keplergl=0.3.2
  

